/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.catrina.ui;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import mx.itson.catrina.entities.AccountStatement;
import mx.itson.catrina.entities.Transactions;

/**
 *
 * @author angel
 */
public class FromRecipe extends javax.swing.JFrame {
AccountStatement accountStatement = null;
    /**
     * Creates new form FromRecipe
     */
    public FromRecipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblECuenta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnLoad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        lblClabe = new javax.swing.JLabel();
        lblCurrency = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblDeposits = new javax.swing.JLabel();
        lblWithdrawals = new javax.swing.JLabel();
        lblFinalBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblECuenta.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        lblECuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblECuenta.setText("Estado de Cuenta");
        lblECuenta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 153)));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLoad.setText("Load Field...");
        BtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoadActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setText("ACCOUNT STATEMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setText("ACCOUNT:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("CLABE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setText("CURRENCY:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel1.add(lblAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, 20));
        jPanel1.add(lblClabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, 20));
        jPanel1.add(lblCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 20));

        jLabel5.setText("USER DATA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 790, -1));

        jLabel6.setText("NAME:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        jLabel7.setText("RFC:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        jLabel8.setText("ADDRESS:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        jLabel9.setText("CITY:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jLabel10.setText("ZIP CODE:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 36, 60, 20));
        jPanel1.add(lblRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 56, 60, 20));
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 76, 60, 20));
        jPanel1.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 96, 60, 20));
        jPanel1.add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 116, 60, 20));

        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Description", "Amount", "Type"
            }
        ));
        jScrollPane7.setViewportView(tblTransactions);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 790, 180));

        jLabel11.setText("PERIOD SUMMARY");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel12.setText("DEPOSITS:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel13.setText("WITHDRAWALS:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel14.setText("FINAL BALANCE:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(lblDeposits, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 176, 60, 20));
        jPanel1.add(lblWithdrawals, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 206, 60, 20));
        jPanel1.add(lblFinalBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 236, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblECuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblECuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void BtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoadActionPerformed
        //;3.exit;
        try{
          
          //se cita los datos y valores como name, rfc, address, city y zipcode para acomodarles en sus casillas  
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
                File file = fileChooser.getSelectedFile();
                byte fileBytes[] = Files.readAllBytes(file.toPath());

                String content = new String(fileBytes, StandardCharsets.UTF_8);
                
                
                //se acomodan los datos en sus casillas citando su get and set
                accountStatement = new AccountStatement().deserialize(content);
                lblName.setText("NAME " + accountStatement.getCustomer().getName().toUpperCase());
                lblRfc.setText("RFC " + accountStatement.getCustomer().getRFC());
                lblAddress.setText("ADDRESS " + accountStatement.getCustomer().getAddress());
                lblCity.setText("CITY " + accountStatement.getCustomer().getCity());
                lblZipCode.setText("Zip Code " + accountStatement.getCustomer().getZipCode());
                
                Locale local = new Locale("es","MX");
                NumberFormat CurrencyFormat = NumberFormat.getCurrencyInstance(local);
                lblAccount.setText("ACCOUNT: " + accountStatement.getAccount());
                lblClabe.setText("CLABE: " + accountStatement.getClabe());
                lblCurrency.setText("CURRENCY: " + accountStatement.getCurrency());    
                
                
                //aqui los datos se acomodan en la tabla dependiendo su valor
                
                if(accountStatement != null){
                    DefaultTableModel model = (DefaultTableModel)tblTransactions.getModel();
                    model.setRowCount(0);
                    for(Transactions d: accountStatement.getTransactions()){
                        model.addRow(new Object[] {
                            d.getType(),
                            d.getDescription()
                        });
                        for(Transactions n: accountStatement.getTransactionsesOp()){
                            model.addRow(new Object[] {
                                n.getDate(),
                                n.getDescription(),
                                n.getAmount(),
                                n.getType()
                            });
                            

                        }
                    }

                }
            }
        } catch(IOException ex){
            System.err.print("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_BtnLoadActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromRecipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLoad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblClabe;
    private javax.swing.JLabel lblCurrency;
    private javax.swing.JLabel lblDeposits;
    private javax.swing.JLabel lblECuenta;
    private javax.swing.JLabel lblFinalBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblWithdrawals;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTable tblTransactions;
    // End of variables declaration//GEN-END:variables
}
